-- @description The Little Cavern Dashboard
-- @version 5.8
-- @author Jordi Molas - The Little Cavern Studio
-- @about
--   Dynamic dashboard for launching sessions and recent projects.
--   
--   =========================================
--   🛑 AUTO-BOOT SETUP INSTRUCTIONS 🛑
--   =========================================
--   To make this dashboard open automatically when Reaper starts:
--   
--   1. Open the Actions List in Reaper (shortcut: ?).
--   2. Search for "TLC Dashboard".
--   3. Right-click on it and select "Copy selected action command ID".
--   4. In the top menu, go to: Extensions > SWS Options > Enable global startup action.
--   5. Paste the ID and hit OK!
-- @provides
--   [main] TLC_Dashboard.lua
--   [main] Session Builder.lua