name: ReaPack Index
on: [push]
jobs:
  index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install and Run Indexer
        run: |
          gem install --user-install reapack-index
          $(gem src)/bin/reapack-index --commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}