name: ReaPack Index
on: [push]
jobs:
  index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install and Run Indexer
        run: |
          gem install --user-install reapack-index
          git config user.name "The Little Cavern Bot"
          git config user.email "thelittlecavernstudio-dev@users.noreply.github.com"
          # Forzamos el escaneo de la carpeta jmolas_scripts
          /home/runner/.local/share/gem/ruby/3.2.0/bin/reapack-index --commit --amend --name "The Little Cavern Studio"
          git push origin main --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}